### ISSUE TITLE
Checkout Button defective

### ISSUE THREAD

**Issue by Nirdosh01** [Aayushrai001/Farmket#6]
Expected Behavior: 
                                 Clicking on the checkout button should trigger the initiation of the checkout process, guiding users through the necessary steps to finalize their orders and complete transactions seamlessly.

Actual Behavior:
                             The checkout button fails to function as intended, preventing users from progressing to checkout and completing their purchases. This issue delay the overall user experience and slow down the website's ability to facilitate successful transactions.

**Comment by Aayushrai001** [comment]
This issue has been resolved. This was due to not declaring count variable in the backend code.

**Comment by PrashanBasnet7** [comment]
The issue has been solved.

**Comment by Aayushrai001** [comment]
Completed

**Comment by Aayushrai001** [comment]
complete
