### ISSUE TITLE
Inability to Update Product Approval Status in Database

### ISSUE THREAD

**Issue by Nirdosh01** [Aayushrai001/Farmket#7]
Admin can't update product approval status in the database despite dashboard attempts. This leads to unreliability between dashboard and stored data, hampering product management. Approved products may remain inaccessible to users due to database update failures.

**Comment by Aayushrai001** [comment]
This issue has been resolved. This was due to utilizing the incorrect query in the backend code.

**Comment by Aayushrai001** [comment]
This issue has been resolved. This was due to utilizing the incorrect query in the backend code.
