### ISSUE TITLE
Failure to Fetch Data and Redirect to User Homepage

### ISSUE THREAD

**Issue by Nirdosh01** [Aayushrai001/Farmket#8]
When users attempting to log in to the Farmket website face a critical issue with the login button. Even after inputting valid credentials such as their phone number and password, clicking the login button does not trigger the expected action of fetching user data and redirecting them to their homepage. This malfunction disrupts the login process, denying users access to their accounts and desired homepage functionalities.

**Comment by Aayushrai001** [comment]
This issue has been resolved. This was due not giving value for the login button.
